export const FETCH_TICKETS = "FETCH_TICKETS";
export const FETCH_TICKETS_USER = "FETCH_TICKETS_USER";
export const ADD_TICKET = "ADD_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
